#title in header
title: "å‘¨æµ·å†›çš„ä¸ªäººåšå®¢"

#main info
#owner
owner: "ç®€ä»‹"
email: haijunzh@hotmail.com
info: "å±…ä½åœ¨ç‘å…¸çš„ä¸€ä½ITå·¥ç¨‹å¸ˆ/ä¸¤ä¸ªå°å­©çš„çˆ¶äº²/ä¸šä½™æˆ·å¤–ä½“è‚²çˆ±å¥½è€…ã€‚"
#description
desc: "ç‚¹æ»´è®°å½•ä¸€äº›ä¸šä½™é—²æš‡æ—¶çš„æ‰€è§æ‰€é—»ã€æ‰€è¡Œæ‰€æ€ã€‚"

#menu
menu:
  æˆ‘çš„ç‘å…¸ç»å…¸: /æˆ‘çš„ç‘å…¸ç»å…¸
  ä½“è‚²å¥èº«: /ä½“è‚²å¥èº«
  å…¸æ»´ç”Ÿæ´»: /å…¸æ»´ç”Ÿæ´»

#index/main page max show posts (in number)
max_post: 4

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
# placename: Earth
# placelink: https://en.wikipedia.org/wiki/Earth
# github: https://github.com/adisaktijrs
# linkedin: https://linkedin.com/in/adisaktijrs
# twitter: https://twitter.com/adisaktijrs
# instagram: https://instagram.com/adisaktijrs
# stackoverflow: https://stackoverflow.com/story/tobiasreithmeier
rss: /atom.xml

# Misc
nanobar: /js/nanobar.min.js
switch_light: â˜€ï¸
switch_dark: ğŸŒ‘

# favicon
#favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: true
disqus_shortname: zhouhaijun-com